### PR TITLE
Develop unitlist object

### PR DESCRIPTION
**Pull request by ingmargoudt**
The unitlist is changed to a separate object (could be a service later), all other classes dont affect the unitlist directly, but modify and query the contents with mutators and accessors. e.g.: ironbane.unitList.push(new Unit()) vs ironbane.getUnitList().addUnit(new Unit());

### CODE REVIEW

**Comment by bsparks** [comment]
Looks good accept

**Comment by markfarrell** [comment]
/src/client/game/js/Game/Player.js Line 606: 

Are you sure "_.each(ironbane.getUnitList().iterate(function() { ... }));" is not supposed to be 
"ironbane.getUnitList().iterate(function() { ... });" ?

**Comment by ingmargoudt** [comment]
Correct. Should be without the _.each() as that is called by the unitlist.iterate() function itself. Will update and commit.

Verstuurd vanaf mijn iPhone

**Comment by markfarrell** [comment]
Accept

**Pull request merged**
