### PR TITLE
Add escape handling for exit prompt

### PR DESCRIPTION
**Pull request by stancoffyn**
pending review and acceptance. Issue request https://github.com/ironbane/IronbaneServer/issues/393

### CODE REVIEW

**Comment by ingmargoudt** [comment]
Can you fix the else if line ?

**Comment by nickjanssen** [comment]
@stancoffyn

**Comment by stancoffyn** [comment]
I'm at work now, will change this when I get home.

**Comment by nickjanssen** [comment]
@stancoffyn are you going to change this?

**Pull request closed without merging**
