### PR TITLE
Webapi

### PR DESCRIPTION
**Pull request by ingmargoudt**
mostly jshint applications, some sql changes

### CODE REVIEW

**Comment by bsparks** [comment]
the only things in here that I disagree with are the changes to nconf.js and index.html. have you tried it with just root: 'ironbaneServer/" the way that I had it setup? I think that should allow the root paths to be used. Also I don't think there is any harm in having the db pw default to 'root' in nconf since it's supposed to get overwritten by config.json.

edit: on second thought perhaps having the relative paths is OK but what you have for the default root path I think doesn't apply and would always be overwritten. I'll try hosting mine in a subfolder like that to see.

**Comment by ingmargoudt** [comment]
Yes pardon me, those are my local changes. I am still trying to get this working on my localhost, as all relative paths bring me back to localhost again. Your suggested solution does not seem to work for me. 
Currently workaround for this is to use:
root: 'http://localhost/IronbaneServer/deploy/web/' in the nconf.js and remove all starting slashes of the relative paths. I know this should not be the solution, as the current implementation works for you. It must be something silly I am overlooking here.

Speaking of config.json, I saw it mentioned in nconf.js...where is that file?

**Comment by bsparks** [comment]
The config.json file is one that you would create. nconf is setup to read that file if present, otherwise use the defaults listed in it. for example the contents of mine looks like this:

`{
    "root": "",
    "server_port": 9080,
    "api_port": 9081
}`

because I'm only overriding a few of them (I have other servers on 8080 for example.

Come to think of it however, how are you even having this localhost issue? Are you hosting the web files in another web server? The game server should be hosting everything now, so I don't see how it would not be at the root already.

For example the url I use to access is this based on my port config: http://localhost:9081/forum so I don't think we even have it setup to be possible for it to be http://localhost:9081/IronbaneServer/forum for example.

I suppose we should prolly rename server_port to socket_port or game_port and api_port to http_port

**Comment by ingmargoudt** [comment]
_incredible facepalm_

that happens when you don't turn on the server.......

working as intended now!

**Comment by bsparks** [comment]
WOOHOO!!! Now we're cookin' with gas!

hmmm so now I think that whole root variable is useless hehe since it's not possible to host it elsewhere, oops why didnt I see that before :dart:

**Comment by bsparks** [comment]
if you can revert those files as well as consoleHandler (i made a couple non mergable changes) then I can merge in

**Comment by ingmargoudt** [comment]
updated the conf.js and index.html back to their original state (or so I hope). I had no issues with merging consoleHandler.js

**Pull request merged**
