### PR TITLE
Webapi

### PR DESCRIPTION
**Pull request by ingmargoudt**
some new updates from my side
starting to fiddle a bit with the registration form. Need review from bsparks on these changess, as this is my first commit with angularJS.

### CODE REVIEW

**Comment by nickjanssen** [comment]
Hey Ingmar, glad to see another pull request :) Could you rebase first? You should be able to do `git pull --rebase upstream webapi`. Your pull request currently can't be automatically merged currently because of conflicts.

**Comment by ingmargoudt** [comment]
I always do a remote fetch from the upstream and then I push to my own repo. I didn't have conflicts there. Will do a rebase if you want.

**Comment by nickjanssen** [comment]
A fetch doesn't do anything, it just tells Git that there are updates. I just opened your repo, the last commit that you have from the upstream webapi branch is 411139357530a4d0a8c1316a7e0d9c0376c9fc2b so your repo isn't up to date. You need to do a rebase before Ben can merge it in, so that your repo includes the last commits (e.g. 51f42da07371c4922d1f2bd9b11f9d6343bbfe64)
You can always review the commits you have using `git log`and check whether or not you have the latest commits in your branch.

**Comment by ingmargoudt** [comment]
ok, will work on it :)

**Comment by ingmargoudt** [comment]
could you check again? did a full rebase

**Comment by nickjanssen** [comment]
Something went wrong here...what exactly did you do? I just tried it from your branch, using `git pull --rebase upstream webapi` and it worked fine for me.

A successful rebase means that your commits will be applied on top of Ben's commits. This is where the message `First, rewinding head to replay your work on top of it...` comes from if you use Git Bash. In your case however, Ben's commits are still on top and your commits are somehow squashed in between. 

Can you try again? Here's what you need to do:
- Just open a Git Bash, make sure you have your local webapi branch open and type `git reset --hard 68d2326aefcd65391cb8ef2d1230f8c855d87db3` to reset your branch to your latest commit 68d2326aefcd65391cb8ef2d1230f8c855d87db3.
- Confirm that you have the upstream remote set correctly. If not, add it using `git remote add upstream https://github.com/ironbane/IronbaneServer.git`
- Now, rebase using `git pull --rebase upstream webapi`. You will get conflicts, and you need to fix them before you can continue. On Windows you can use TortoiseGit, right-click the repo folder and go to 'Check for Modifications'. There, make sure you fix the conflicts and mark the files as resolved. Once you're done with that, go back to the Git Bash and type `git rebase --continue` until you are finished.
- Now check your commit history. If everything went well, your commits will be on top, like here:

image

**Comment by ingmargoudt** [comment]
ok...did all that (I did the same steps before), but when I do a git status, I get the message that this branch and the remote branch have diverged.
Probably I was working on a wrong branch, because I played a bit with that in the GIT GUI. If you go to the option: checkout branch, in the git gui, do I need to have local branch / webapi or tracking branch / origin/webapi?

**Pull request merged**
