### PR TITLE
recursion in web/index solved.

### PR DESCRIPTION
**Pull request by ingmargoudt**
recursion in web/index solved.
added routing for forum
added routing for login

remaining issues:
1) when on the forum, the forum layout , as defined by the forum-view, is shown on the screen, but the angular variables between {{}} are not visible. When you console.log the variables as returned by the REST the data is correct

2)
When starting the game, get('/api/forum/news' is used, but this is mapped on the routing get('/api/forum/:boardId'. Needs a unique routing

### CODE REVIEW

**Comment by bsparks** [comment]
one problem is that when you use res.render you are passing the html through the hogan.js template renderer. Both angular and hogan use {{ }} for templates. so, I was planning / hoping to switch from handlebars.

also, I think we may not be able to just bring over all the forum routes directly, I'm sure there are at the very least DB changes that go along with them. for the news forum perhaps we can just test if boardId === 'news' 

im curious if you know which part is solving the recursion

i'll merge it in soon to play around with it

**Comment by ingmargoudt** [comment]
What I saw yesterday while debugging , when the root of the site ('/') was accessed by the routing, immediately after that 'views/login' was accessed. Maybe that started the recursion?
Agree with the boardId==='news' guard.
I understand now the interaction between hogan and angular. Is that also the reason why you sometimes use triple brackets? {{{ }}}. Can we configure hogan to skip parsing {{ }}?

**Comment by ingmargoudt** [comment]
hogan express now uses another delimiter

**Comment by bsparks** [comment]
triple brackets is for unescaped HTML http://mustache.github.io/mustache.5.html

we need to update the game index file with the new delim also

**Pull request merged**
