### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marisusis**

### CODE REVIEW

**Comment by nickjanssen** [comment]
Thanks!

**Comment by samjar** [comment]
Wow, Ironbane! That brings back memories. You guys working on it again, huh?

**Comment by spacegeek224** [comment]
It's a great project

**Comment by TheRestIsATest** [comment]
I know nothing about a reboot, but I'd join if we did one ;)

**Comment by ChaiTeaNunes** [comment]
same here :)

**Comment by nickjanssen** [comment]
@samjar merging that PR felt really good! Hahaha

@Meanapple @ChaiTeaNunes once I have funding, I will! I also really miss it.

**Comment by ghost** [comment]
I miss Ironbane as well, hahah. And there's always Patreon! I pledge a small bit to an MMO mod called "Super Terraria World" that is funding development. Their project reminds me of Ironbane from the pixel art.

**Comment by TheRestIsATest** [comment]
@nickjanssen what would the costs be for a simple server again?

**Comment by marisusis** [comment]
I'd be willing to try and host an Ironbane server.

**Comment by TheRestIsATest** [comment]
We could just try a unity version of ironbane to make the ball rolling.  Are you guys using discord?

**Comment by bsparks** [comment]
I miss it too, count me in whatever happens

**Comment by ghost** [comment]
I'm in Discord, esp. if anyone wants to start a chat or channel. DatapawWolf#5961.

**Comment by TheRestIsATest** [comment]
I'll leave a link for anyone wanting to join
https://discord.gg/b66JQzn

**Pull request merged**
