### PR TITLE
next round of changes to website

### PR DESCRIPTION
**Pull request by bsparks**

### CODE REVIEW

**Comment by ingmargoudt** [comment]
- Missing an sql update: Error: ER_BAD_FIELD_ERROR, unknown column topic.title
- in preferences, the 'old password' field does not listen, you can fill in any random string, or keep it empty, and the new password will still validate

because of the missing sql update, the markdown in posts can not be tested yet

**Comment by nickjanssen** [comment]
@ingmargoudt I did not get any mysql errors, did you run grunt? Posting new thread + replying works fine here. Or do you mean something else? Markdown works fine here.

Indeed, old passwords are ignored currently.

**Comment by bsparks** [comment]
the review items should be corrected now

**Comment by ingmargoudt** [comment]
approved. review items are fixed

**Pull request merged**
