### PR TITLE
working on the next round of website changes

### PR DESCRIPTION
**Pull request by bsparks**

### CODE REVIEW

**Comment by nickjanssen** [comment]
the gravatar still doesn't work; it appears the value is set to `null` when you request it. Couldn't figure out immediately why though, I guess the queries are messed up somehow.

in topic.js I added a console.log

```
                if(p.character_avatar !== 0) {
                    // get character based avatar
                    p.user.avatarUrl = "";
                } else {
                    // do gravatar based
                    console.log(p.gravatar_email);
                    p.user.avatarUrl = gravatar.imageUrl(p.gravatar_email || "404", {"size": "80", "d": "retro"});
                }
```

it echoes `null`for me. The resulting image is probably for the "404" string. Same for user.js

**Comment by bsparks** [comment]
you updated your gravatar_email in prefs? it was working for me

**Comment by nickjanssen** [comment]
Sorry, my fault. Turns out I set the gravatar for the wrong user :P working great!

**Comment by ingmargoudt** [comment]
Approved until 94143a0

**Pull request merged**
